name: 🔁 Auto Update Jiostar M3U

on:
  schedule:
    - cron: "0 */2 * * *"   
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Fetch and convert M3U
        env:
          M3U_URL: ${{ secrets.M3U_URL }}
        run: |
          import re, json, requests

          url = "${{ secrets.M3U_URL }}"
          r = requests.get(url)
          data = r.text.strip().splitlines()

          channels = []
          cookies = []

          current = {}
          for line in data:
              if line.startswith("#EXTINF"):
                  name = re.search(r',(.+)', line)
                  logo = re.search(r'tvg-logo="([^"]+)"', line)
                  group = re.search(r'group-title="([^"]+)"', line)
                  tvgid = re.search(r'tvg-id="([^"]+)"', line)
                  current = {
                      "name": name.group(1) if name else "",
                      "logo": logo.group(1) if logo else "",
                      "group": group.group(1) if group else "",
                      "tvg_id": tvgid.group(1) if tvgid else "",
                      "url": ""
                  }
              elif line.startswith("#EXTHTTP:"):
                  cookie = re.search(r'"cookie":"([^"]+)"', line)
                  if cookie:
                      current["cookie"] = cookie.group(1)
                      cookies.append({"name": current.get("name"), "cookie": cookie.group(1)})
              elif line.startswith("http"):
                  current["url"] = line.strip()
                  if current:
                      channels.append(current)
                      current = {}

          # Save JSON output
          with open("channels.json", "w") as f:
              json.dump(channels, f, indent=2)

          with open("cookie.json", "w") as f:
              json.dump(cookies, f, indent=2)

          # Save filtered M3U
          m3u_output = ["#EXTM3U x-tvg-url=\"https://avkb.short.gy/jioepg.xml.gz\""]
          for c in channels:
              m3u_output.append(f'#EXTINF:-1 tvg-id="{c["tvg_id"]}" group-title="{c["group"]}" tvg-logo="{c["logo"]}",{c["name"]}')
              m3u_output.append(c["url"])
          open("channels.m3u", "w").write("\n".join(m3u_output))

      - name: Commit & push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add channels.json cookie.json channels.m3u
          git commit -m "🔄 Auto updated Jiostar M3U data"
          git push
